apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "nginx-demo-chart.fullname" . }}
  labels:
    {{- include "nginx-demo-chart.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "nginx-demo-chart.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
